[local]
localhost

[mongo]
mongodb.rajesh-lab.shop

[redis]
redis.rajesh-lab.shop

[mysql]
mysql.rajesh-lab.shop

[rabbitmq]
rabbitmq.rajesh-lab.shop

[catalogue]
catalogue.rajesh-lab.shop

[user]
user.rajesh-lab.shop

[cart]
cart.rajesh-lab.shop

[shipping]
shipping.rajesh-lab.shop

[payment]
payment.rajesh-lab.shop

[frontend]
frontend.rajesh-lab.shop