- name: Configuring rabbitmq server
  hosts: rabbitmq
  tasks:
    - name: copying file
      copy:
        src: rabbitmq.repo
        dest: /etc/yum.repos.d/rabbitmq.repo

    - name: installing rabbitmq package
      package:
        name: rabbitmq-server
        state: present
      
    - name: starting the rabbitmq service
      service:
        name: rabbitmq-server
        state: restarted
        enabled: yes
      
    - name: addding username and password
      command:  rabbitmqctl add_user roboshop roboshop123
    
    - name: set set_permissions
      command: rabbitmqctl set_permissions -p / roboshop ".*" ".*" ".*"
