- name: Creating instances
  hosts: local
  connection: local
  vars: 
    name_of_instances: ["mongodb","mysql"]
    image_id: ami-0220d79f3f480ecf5
    domain_name: rajesh-lab.shop 
    action: create
    sg_common: roboshop-common
    my_ip: 136.185.89.27/32
  tasks:
    - name: start multiple instances
      amazon.aws.ec2_instance:
        name: "roboshop-{{item}}"
        instance_type: t3.micro
        image_id: "{{ image_id }}"
        region: us-east-1
        security_groups: 
          - "{{ sg_common }}"
          - "roboshop-{{ item }}"
        tags:
          foo: "roboshop-{{ item }}"
      loop: "{{ name_of_instances }}"
      register: ec2_output
      when: action=="create"
    
    - name: Printing ec2_output
      debug:
        msg: "{{ ec2_output }}"

    - name: Printing Ip_adress
      debug:
        msg: "Item_name is {{item.item}} and ip address {{item.instances[0].[private_ip_address}}"
      loop: "{{ ec2_output.results }}"


